version: 2.1

jobs:
  say-hello:
    docker:
      - image: alpine:latest
    steps:
      - run: echo 'Hello, '

  say-world:
    docker:
      - image: alpine:latest
    
    steps:
      - run: echo 'world!'

  print-my-name:
    docker:
      - image: alpine:latest

    steps:
      - run: 
        name: "Print My Name"
        command: |
          echo "Hello $MY_NAME"

workflows:
  welcome:
    jobs:
      - say-hello
      - say-world:
          requires:
            - say-hello

      - print-my-name:
          requires:
            - say-world
