version: 2.1

jobs:
  say_hello:
    docker:
      - image: alpine:latest
    steps:
      - run: echo 'Hello, '

  say_world:
    docker:
      - image: alpine:latest
    
    steps:
      - run: echo 'world!'

workflows:
  welcome:
    jobs:
      - say_hello
      - say_world:
        requires:
          - say_hello
